from __future__ import annotations

import subprocess
import sys
import threading
import uuid
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response

MAX_UPLOAD_BYTES = 8 * 1024 * 1024
PROCESS_TIMEOUT_SECONDS = 180
MAX_CONCURRENT_JOBS = 4
STDERR_TAIL_CHARS = 1000
INDEX_HTML = Path(__file__).resolve().parent / "index.html"
_jobs = threading.Semaphore(MAX_CONCURRENT_JOBS)

app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next) -> Response:  # type: ignore[no-untyped-def]
        response = await call_next(request)
        response.headers.update({
            "X-Content-Type-Options": "nosniff",
            "X-Frame-Options": "DENY",
            "Referrer-Policy": "no-referrer",
            "Content-Security-Policy": "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; form-action 'self'",
        })
        return response


app.add_middleware(SecurityHeadersMiddleware)


@app.get("/", response_class=HTMLResponse)
def index() -> HTMLResponse:
    return HTMLResponse(INDEX_HTML.read_text(encoding="utf-8"))


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/api/convert")
def convert(file: UploadFile = File(...)) -> FileResponse:
    if not file.filename or not Path(file.filename).suffix:
        raise HTTPException(status_code=400, detail="Invalid file name.")
    body = file.file.read(MAX_UPLOAD_BYTES + 1)
    if len(body) > MAX_UPLOAD_BYTES:
        raise HTTPException(status_code=413, detail="File too large (max 8MB).")
    if not _jobs.acquire(blocking=False):
        raise HTTPException(status_code=429, detail="Server busy. Please try again shortly.")
    try:
        # We'd better don't trust the filename from the client, which may contain 
        # path injection attack or other malicious content.
        # So input_path and output_path are generated by uuid.
        # And the musicxml file we returned to client is always "homr.musicxml"
        input_path = Path("/tmp") / f"{uuid.uuid4().hex}{Path(file.filename).suffix}"
        input_path.write_bytes(body)
        try:
            completed = subprocess.run(
                [sys.executable, "-m", "homr.main", str(input_path)],
                timeout=PROCESS_TIMEOUT_SECONDS, capture_output=True, text=True,
            )
        except subprocess.TimeoutExpired:
            raise HTTPException(status_code=504, detail="Conversion timed out.")
        except Exception:
            raise HTTPException(status_code=422, detail=f"Conversion failed.")
        output_path = input_path.with_suffix(".musicxml")
        if not output_path.is_file():
            Path(f"{input_path}.log").write_text(completed.stderr, encoding="utf-8")
            raise HTTPException(status_code=422, detail=f"Conversion failed.")

        return FileResponse(output_path, media_type="application/vnd.recordare.musicxml+xml", filename=f"homr.musicxml")
    finally:
        _jobs.release()
